<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\UniqueConstraintViolationException;

class TuitionPost extends Model
{
    protected $fillable = [
        'tuition_code',
        'guardian_id',
        'title',
        'division_id',
        'district_id',
        'subdistrict_id',
        'address_line',
        'salary_type',
        'salary_min',
        'salary_max',
        'days_per_week',
        'preferred_time_slots',
        'duration_months',
        'tutor_gender_preference',
        'required_experience_months',
        'special_requirements',
        'status',
        'published_at',
    ];

    protected function casts(): array
    {
        return [
            'published_at' => 'datetime',
            'preferred_time_slots' => 'array',
        ];
    }

    protected static function booted(): void
    {
        static::creating(function (TuitionPost $post): void {
            if (! empty($post->tuition_code)) {
                return;
            }

            // Only consider canonical codes ("TID" + 8 digits = 11 chars) so
            // non-conforming codes (e.g. seeded "TIDSTR…" values) don't break
            // the numbering. For fixed-width zero-padded codes, lexicographic
            // order matches numeric order. LENGTH() is portable across MySQL/SQLite.
            $last = self::query()
                ->where('tuition_code', 'like', 'TID%')
                ->whereRaw('LENGTH(tuition_code) = 11')
                ->orderByDesc('tuition_code')
                ->value('tuition_code');

            $next = $last ? (int) substr($last, 3) + 1 : 1;

            $post->tuition_code = 'TID'.str_pad($next, 8, '0', STR_PAD_LEFT);
        });
    }

    /**
     * Save the model, retrying on tuition_code collisions so concurrent
     * creates (which may compute the same next code) don't fail. The losing
     * insert clears its auto-generated code and regenerates a fresh one via
     * the "creating" hook, which now sees the committed competing row.
     */
    public function save(array $options = []): bool
    {
        // Only auto-generated codes on a new record are safe to retry; a
        // caller-supplied code or an update should surface the error as-is.
        $autoGenerated = ! $this->exists && empty($this->tuition_code);

        for ($attempt = 1; ; $attempt++) {
            try {
                return parent::save($options);
            } catch (UniqueConstraintViolationException $e) {
                if (! $autoGenerated || $attempt >= 5 || ! str_contains($e->getMessage(), 'tuition_code')) {
                    throw $e;
                }

                // Force the "creating" hook to recompute on the next attempt.
                $this->tuition_code = null;
                usleep(random_int(1_000, 5_000));
            }
        }
    }

    public function guardian(): BelongsTo
    {
        return $this->belongsTo(User::class, 'guardian_id');
    }

    public function applications(): HasMany
    {
        return $this->hasMany(TuitionApplication::class);
    }

    public function students(): HasMany
    {
        return $this->hasMany(TuitionPostStudent::class);
    }

    public function preferredUniversities(): BelongsToMany
    {
        return $this->belongsToMany(University::class, 'tuition_post_preferred_university');
    }
}
